# Generated by Django 4.0.6 on 2024-08-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_remove_instructor_created_by_admin_and_more'),
        ('admin_page_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.student')),
            ],
            options={
                'db_table': 'activation_requests',
            },
        ),
    ]
