# Generated by Django 4.0.6 on 2024-08-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
