# Generated by Django 4.0.6 on 2024-08-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_profile_cover_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_photo',
        ),
    ]
