# Generated by Django 4.0.6 on 2024-08-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_remove_profile_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
    ]
