# Generated by Django 4.0.6 on 2024-08-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_profile_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='created_by_admin',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='description',
        ),
    ]
